site_name: Quoll
site_description: Документация проекта Quoll

theme:
  name: material
  palette:
    primary: pink
    accent: pink

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html

nav:
  - Главная: index.md
  - Установка: installation.md

  - Функциональная документация:
      - Назначение и задача: Функциональная документация/Назначение и задача.md
      - Роли и права: Функциональная документация/Роли и права.md
      - Workflow: Функциональная документация/Workflow.md
      - Модель данных: Функциональная документация/Модель данных.md
      - Методы обработки данных: Функциональная документация/Методы обработки данных.md
      - Интеграции и JSON: Функциональная документация/Интеграции и JSON.md
      - Термины и сокращения: Функциональная документация/Термины и сокращения.md

  - Техническая документация:
      - Архитектура: Техническая документация/Архитектура.md
      - Стек. Обоснование. Библиотеки: Техническая документация/Стек. Обоснование. Библиотеки.md
      - API - Swagger UI: Техническая документация/API - Swagger UI.md
      - Безопасность и персональные данные: Техническая документация/Безопасность и персональные данные.md
      - Производительность: Техническая документация/Производительность.md
      - Сборка. Установка. Запуск: Техническая документация/Сборка. Установка. Запуск.md
      - Условия и ограничения: Техническая документация/Условия и ограничения.md

  - Справочная документация:
      - Диаграммы последовательностей: Справочная документация/Диаграммы последовательностей.md
      - Физические схемы базы данных: Справочная документация/Физические схемы базы данных.md
      - Коды ошибок: Справочная документация/Коды ошибок.md
      - Примеры JSON: Справочная документация/Примеры JSON.md
      - Руководство администратора: Справочная документация/Руководство администратора.md
      - Руководство пользователя: Справочная документация/Руководство пользователя.md
