site_name: Quoll
site_description: Документация проекта Quoll
site_url: http://127.0.0.1:8000/mkdocs/

theme:
  name: material
  palette:
    primary: pink
    accent: pink

nav:
  - Главная: index.md
  - Установка: installation.md
