services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: quoll
      POSTGRES_PASSWORD: 1223334444
      POSTGRES_DB: quoll_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --import-realm
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: megapassword
    depends_on:
      - postgres
    volumes:
      - ./keycloak-start-settings.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"
  garage:
    image: dxflrs/garage:v2.4.1
    command: /garage server --single-node --default-bucket
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: GK000000000000000000000001
      GARAGE_DEFAULT_SECRET_KEY: "0000000000000000000000000000000000000000000000000000000000000001"
      GARAGE_DEFAULT_BUCKET: quoll-storage
    ports:
      - "3900:3900"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data

volumes:
  pgdata:
  garage-meta:
  garage-data:
