"""integration stubs: lms stats, enrollments, mappings, queue, runs, proposals

Revision ID: 092e8988e5c7
Revises: 57ea0170aa1e
Create Date: 2026-09-29 01:58:32.621985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "092e8988e5c7"
down_revision: Union[str, Sequence[str], None] = "57ea0170aa1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_mappings",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("external_key", sa.String(length=255), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "kind IN ('COURSE', 'UNIVERSITY', 'PROGRAM')",
            name=op.f("chk_integration_mapping_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_integration_mappings_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_mappings")),
    )
    op.create_index(
        "uq_integration_mappings_key",
        "integration_mappings",
        ["kind", "external_key"],
        unique=True,
    )
    op.create_table(
        "integration_runs",
        sa.Column("flow", sa.String(length=10), nullable=False),
        sa.Column("trigger", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "counters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "flow IN ('I2', 'I1', 'B1', 'B2', 'EXPORT')",
            name=op.f("chk_integration_run_flow"),
        ),
        sa.CheckConstraint(
            "status IN ('DONE', 'FAILED')", name=op.f("chk_integration_run_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('SCHEDULE', 'MANUAL', 'FILE')",
            name=op.f("chk_integration_run_trigger"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_integration_runs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_runs")),
    )
    op.create_index(
        "ix_integration_runs_flow", "integration_runs", ["flow", "id"], unique=False
    )
    op.create_table(
        "integration_unmatched",
        sa.Column("flow", sa.String(length=5), nullable=False),
        sa.Column("record_key", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("mapping_kind", sa.String(length=20), nullable=False),
        sa.Column("external_key", sa.String(length=255), nullable=False),
        sa.Column("record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "(status = 'PENDING') = (decided_at IS NULL)",
            name=op.f("chk_integration_unmatched_decided"),
        ),
        sa.CheckConstraint(
            "code IN ('INT-404', 'INT-409')",
            name=op.f("chk_integration_unmatched_code"),
        ),
        sa.CheckConstraint(
            "flow IN ('B1', 'B2')", name=op.f("chk_integration_unmatched_flow")
        ),
        sa.CheckConstraint(
            "mapping_kind IN ('COURSE', 'UNIVERSITY', 'PROGRAM')",
            name=op.f("chk_integration_unmatched_mapping_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED')",
            name=op.f("chk_integration_unmatched_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_integration_unmatched_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_unmatched")),
    )
    op.create_index(
        "ix_integration_unmatched_key",
        "integration_unmatched",
        ["mapping_kind", "external_key"],
        unique=False,
    )
    op.create_index(
        "uq_integration_unmatched_pending",
        "integration_unmatched",
        ["flow", "record_key"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "lms_stats",
        sa.Column("university_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("students", sa.Integer(), nullable=False),
        sa.Column("streams", sa.Integer(), nullable=False),
        sa.Column("teachers_trained", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "source IN ('LMS', 'FILE')", name=op.f("chk_lms_stats_source")
        ),
        sa.CheckConstraint("streams >= 0", name=op.f("chk_lms_stats_streams")),
        sa.CheckConstraint("students >= 0", name=op.f("chk_lms_stats_students")),
        sa.CheckConstraint(
            "teachers_trained IS NULL OR teachers_trained >= 0",
            name=op.f("chk_lms_stats_teachers"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["it_programs.id"],
            name=op.f("fk_lms_stats_program_id_it_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_lms_stats_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lms_stats")),
    )
    op.create_index(
        op.f("ix_lms_stats_program_id"), "lms_stats", ["program_id"], unique=False
    )
    op.create_index(
        "uq_lms_stats_pair", "lms_stats", ["university_id", "program_id"], unique=True
    )
    op.create_table(
        "site_enrollments",
        sa.Column("order_number", sa.String(length=255), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("stream", sa.Integer(), nullable=False),
        sa.Column("enrolled_on", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("email_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "source IN ('SITE', 'FILE')", name=op.f("chk_site_enrollment_source")
        ),
        sa.CheckConstraint("stream >= 0", name=op.f("chk_site_enrollment_stream")),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["it_programs.id"],
            name=op.f("fk_site_enrollments_program_id_it_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_enrollments")),
        sa.UniqueConstraint(
            "order_number", name=op.f("uq_site_enrollments_order_number")
        ),
    )
    op.create_index(
        op.f("ix_site_enrollments_email_fingerprint"),
        "site_enrollments",
        ["email_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_enrollments_program_id"),
        "site_enrollments",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "integration_proposals",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("university_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("workflow_id", sa.Integer(), nullable=True),
        sa.Column("result_interaction_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "(status = 'PENDING') = (decided_at IS NULL)",
            name=op.f("chk_integration_proposal_decided"),
        ),
        sa.CheckConstraint(
            "kind IN ('CREATE_INTERACTION', 'ADD_PROGRAM')",
            name=op.f("chk_integration_proposal_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED')",
            name=op.f("chk_integration_proposal_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_integration_proposals_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["it_programs.id"],
            name=op.f("fk_integration_proposals_program_id_it_programs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result_interaction_id"],
            ["interactions.id"],
            name=op.f("fk_integration_proposals_result_interaction_id_interactions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_integration_proposals_university_id_universities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_integration_proposals_workflow_id_workflows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_proposals")),
    )
    op.create_index(
        op.f("ix_integration_proposals_program_id"),
        "integration_proposals",
        ["program_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_proposals_university_id"),
        "integration_proposals",
        ["university_id"],
        unique=False,
    )
    op.create_index(
        "uq_integration_proposals_pending",
        "integration_proposals",
        ["kind", "university_id", "program_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_integration_proposals_pending",
        table_name="integration_proposals",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        op.f("ix_integration_proposals_university_id"),
        table_name="integration_proposals",
    )
    op.drop_index(
        op.f("ix_integration_proposals_program_id"), table_name="integration_proposals"
    )
    op.drop_table("integration_proposals")
    op.drop_index(op.f("ix_site_enrollments_program_id"), table_name="site_enrollments")
    op.drop_index(
        op.f("ix_site_enrollments_email_fingerprint"), table_name="site_enrollments"
    )
    op.drop_table("site_enrollments")
    op.drop_index("uq_lms_stats_pair", table_name="lms_stats")
    op.drop_index(op.f("ix_lms_stats_program_id"), table_name="lms_stats")
    op.drop_table("lms_stats")
    op.drop_index(
        "uq_integration_unmatched_pending",
        table_name="integration_unmatched",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_integration_unmatched_key", table_name="integration_unmatched")
    op.drop_table("integration_unmatched")
    op.drop_index("ix_integration_runs_flow", table_name="integration_runs")
    op.drop_table("integration_runs")
    op.drop_index("uq_integration_mappings_key", table_name="integration_mappings")
    op.drop_table("integration_mappings")
    # ### end Alembic commands ###
