"""stall thresholds and counting, branch pause, active and passive slots

Revision ID: 0beee173885d
Revises: 79b9e3f52fea
Create Date: 2026-09-27 23:28:14.056443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0beee173885d"
down_revision: Union[str, Sequence[str], None] = "79b9e3f52fea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


HISTORY_KINDS = (
    "TRANSITION",
    "CLOSE",
    "REOPEN",
    "RELOCATION",
    "REJECTION",
    "ROLLBACK",
    "CANCEL",
    "PAUSE",
    "UNPAUSE",
    "BRANCH_ADDED",
    "BRANCH_REMOVED",
    "SA_OPENED",
    "SA_APPROVED",
    "SA_REJECTED",
    "LICENSE_EXTENDED",
    "CONTRACT_EXTENDED",
    "IMPORT",
    "COMMENT",
)
CHECKS = (
    ("chk_stage_stall_days", "stages", "stall_days IS NULL OR stall_days > 0"),
    (
        "chk_stage_passive_after_days",
        "stages",
        "passive_after_days IS NULL OR (passive_after_days > 0 AND is_branch_stage)",
    ),
    ("chk_interaction_slot", "interactions", "slot IN ('ACTIVE', 'PASSIVE')"),
    (
        "chk_interaction_passive_after_signing",
        "interactions",
        "slot = 'ACTIVE' OR no_return_at IS NOT NULL",
    ),
    (
        "chk_branch_pause_state",
        "branches",
        "(pause_state = 'ACTIVE' AND paused_until IS NULL) OR "
        "(pause_state = 'PAUSED_MANUAL' AND paused_until IS NULL) OR "
        "(pause_state = 'PAUSED_TIMED' AND paused_until IS NOT NULL)",
    ),
    (
        "chk_branch_closed_not_paused",
        "branches",
        "closed_at IS NULL OR pause_state = 'ACTIVE'",
    ),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches", sa.Column("stall_since", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "branches",
        sa.Column(
            "pause_state", sa.String(length=30), server_default="ACTIVE", nullable=False
        ),
    )
    op.add_column(
        "branches", sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("branches", sa.Column("pause_comment", sa.Text(), nullable=True))
    op.add_column(
        "interactions",
        sa.Column("stall_since", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "interactions",
        sa.Column(
            "stall_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "interactions",
        sa.Column("warn_days", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "interactions",
        sa.Column(
            "slot", sa.String(length=10), server_default="ACTIVE", nullable=False
        ),
    )
    op.add_column(
        "interactions",
        sa.Column("slot_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_interactions_active_slots",
        "interactions",
        ["owner_id"],
        unique=False,
        postgresql_where=sa.text("slot = 'ACTIVE' AND closed_at IS NULL"),
    )
    op.add_column("stages", sa.Column("stall_days", sa.Integer(), nullable=True))
    op.add_column(
        "stages", sa.Column("passive_after_days", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workflows",
        sa.Column(
            "warn_days",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[60, 30]'::jsonb"),
            nullable=False,
        ),
    )
    for name, table, condition in CHECKS:
        op.create_check_constraint(name, table, condition)
    op.drop_constraint(
        "chk_stage_history_kind", "interaction_stage_history", type_="check"
    )
    op.create_check_constraint(
        "chk_stage_history_kind",
        "interaction_stage_history",
        "kind IN ("
        + ", ".join(f"'{k}'" for k in (*HISTORY_KINDS, "SLOT_PASSIVE", "SLOT_ACTIVE"))
        + ")",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chk_stage_history_kind", "interaction_stage_history", type_="check"
    )
    op.create_check_constraint(
        "chk_stage_history_kind",
        "interaction_stage_history",
        "kind IN (" + ", ".join(f"'{k}'" for k in HISTORY_KINDS) + ")",
    )
    for name, table, _ in CHECKS:
        op.drop_constraint(name, table, type_="check")
    op.drop_column("workflows", "warn_days")
    op.drop_column("stages", "passive_after_days")
    op.drop_column("stages", "stall_days")
    op.drop_index(
        "ix_interactions_active_slots",
        table_name="interactions",
        postgresql_where=sa.text("slot = 'ACTIVE' AND closed_at IS NULL"),
    )
    op.drop_column("interactions", "slot_changed_at")
    op.drop_column("interactions", "slot")
    op.drop_column("interactions", "warn_days")
    op.drop_column("interactions", "stall_overrides")
    op.drop_column("interactions", "stall_since")
    op.drop_column("branches", "pause_comment")
    op.drop_column("branches", "paused_until")
    op.drop_column("branches", "pause_state")
    op.drop_column("branches", "stall_since")
    # ### end Alembic commands ###
