"""interaction author

Revision ID: 228648134f57
Revises: 454591147c79
Create Date: 2026-09-24 22:38:41.477984

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "228648134f57"
down_revision: str | Sequence[str] | None = "454591147c79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions", sa.Column("created_by", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_interactions_created_by"), "interactions", ["created_by"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_interactions_created_by_users"),
        "interactions",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_interactions_created_by_users"), "interactions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_interactions_created_by"), table_name="interactions")
    op.drop_column("interactions", "created_by")
    # ### end Alembic commands ###
