"""document kinds, contract details on documents, sub-steps

Revision ID: 23c2a2979af2
Revises: f938482991a0
Create Date: 2026-09-27 18:17:30.757891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c2a2979af2'
down_revision: Union[str, Sequence[str], None] = 'f938482991a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SYSTEM_KINDS = {"CONTRACT", "SUPPLEMENTARY_AGREEMENT", "OTHER"}
KINDS = [
    ("CONTRACT", "Договор"),
    ("SUPPLEMENTARY_AGREEMENT", "Допсоглашение"),
    ("CONTRACT_DRAFT", "Проект договора / пакет документов обмена"),
    ("MEETING_PROTOCOL", "Протокол встречи"),
    ("PRESENTATION", "Презентация"),
    ("TRANSFER_ACT", "Акт приёма-передачи"),
    ("LICENSE", "Лицензия / лицензионный сертификат"),
    ("IMPLEMENTATION_PROOF", "Подтверждение внедрения"),
    ("TRAINED_LIST", "Список обученных / сертификаты преподавателей"),
    ("WORK_PROGRAM", "Рабочая программа дисциплины"),
    ("LEARNING_MATERIALS", "Учебные материалы / документация продукта"),
    ("IMPLEMENTATION_REPORT", "Отчёт о ходе внедрения"),
    ("OTHER", "Другое"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_kinds',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_kinds')),
    sa.UniqueConstraint('code', name=op.f('uq_document_kinds_code'))
    )
    # коды - ключи воркфлоу и интеграций (контракт v0.5, прил. А)
    kinds = sa.table(
        "document_kinds",
        sa.column("code", sa.String),
        sa.column("label", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        kinds,
        [
            {"code": code, "label": label, "is_system": code in SYSTEM_KINDS}
            for code, label in KINDS
        ],
    )
    op.add_column('interaction_documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('interaction_documents', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('interaction_documents', sa.Column('contract_signed_at', sa.Date(), nullable=True))
    op.add_column('interaction_documents', sa.Column('contract_valid_until', sa.Date(), nullable=True))
    op.alter_column('interaction_documents', 'kind',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.create_foreign_key(op.f('fk_interaction_documents_kind_document_kinds'), 'interaction_documents', 'document_kinds', ['kind'], ['code'], ondelete='RESTRICT')
    op.create_check_constraint(
        "chk_document_other_described",
        "interaction_documents",
        "kind <> 'OTHER' OR description IS NOT NULL",
    )
    op.create_check_constraint(
        "chk_document_contract_fields",
        "interaction_documents",
        "kind = 'CONTRACT' OR (contract_number IS NULL AND "
        "contract_signed_at IS NULL AND contract_valid_until IS NULL)",
    )
    op.create_check_constraint(
        "chk_document_contract_number",
        "interaction_documents",
        "kind <> 'CONTRACT' OR contract_number IS NOT NULL",
    )
    op.add_column('stages', sa.Column('parent_stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_stages_parent_stage_id_stages'), 'stages', 'stages', ['parent_stage_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stages_parent_stage_id_stages'), 'stages', type_='foreignkey')
    op.drop_column('stages', 'parent_stage_id')
    op.drop_constraint(op.f('fk_interaction_documents_kind_document_kinds'), 'interaction_documents', type_='foreignkey')
    op.alter_column('interaction_documents', 'kind',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('interaction_documents', 'contract_valid_until')
    op.drop_column('interaction_documents', 'contract_signed_at')
    op.drop_column('interaction_documents', 'contract_number')
    op.drop_column('interaction_documents', 'description')
    op.drop_table('document_kinds')
    # ### end Alembic commands ###
