"""block c: archived stages, graph constraints, requests, documents

Revision ID: 261270c7dde5
Revises: 228648134f57
Create Date: 2026-09-24 23:47:30.683448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "261270c7dde5"
down_revision: str | Sequence[str] | None = "228648134f57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=255), nullable=True),
        sa.Column("replaces_document_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_interaction_documents_attachment_id_attachments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_interaction_documents_interaction_id_interactions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaces_document_id", "interaction_id"],
            ["interaction_documents.id", "interaction_documents.interaction_id"],
            name="fk_documents_replaces_same_interaction",
            ondelete="SET NULL (replaces_document_id)",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
            name=op.f("fk_interaction_documents_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_interaction_documents_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_documents")),
        sa.UniqueConstraint(
            "attachment_id", name=op.f("uq_interaction_documents_attachment_id")
        ),
        sa.UniqueConstraint("id", "interaction_id", name="uq_documents_id_interaction"),
    )
    op.create_index(
        op.f("ix_interaction_documents_interaction_id"),
        "interaction_documents",
        ["interaction_id"],
        unique=False,
    )
    op.create_index(
        "uq_documents_replaces",
        "interaction_documents",
        ["replaces_document_id"],
        unique=True,
        postgresql_where=sa.text("replaces_document_id IS NOT NULL"),
    )
    op.create_table(
        "interaction_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=True),
        sa.Column("from_owner_id", sa.String(length=255), nullable=True),
        sa.Column("target_manager_id", sa.String(length=255), nullable=True),
        sa.Column("target_stage_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'PENDING') = (decided_at IS NULL)",
            name=op.f("chk_request_decided"),
        ),
        sa.CheckConstraint(
            "kind <> 'CLOSE' OR (target_stage_id IS NOT NULL AND target_manager_id IS NULL)",
            name=op.f("chk_request_close_target"),
        ),
        sa.CheckConstraint(
            "kind <> 'TRANSFER' OR target_stage_id IS NULL",
            name=op.f("chk_request_transfer_target"),
        ),
        sa.CheckConstraint(
            "kind IN ('TRANSFER', 'CLOSE')", name=op.f("chk_request_kind")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("chk_request_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_interaction_requests_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_owner_id"],
            ["users.id"],
            name=op.f("fk_interaction_requests_from_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_interaction_requests_interaction_id_interactions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_interaction_requests_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_manager_id"],
            ["users.id"],
            name=op.f("fk_interaction_requests_target_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_stage_id"],
            ["stages.id"],
            name=op.f("fk_interaction_requests_target_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_requests")),
    )
    op.create_index(
        op.f("ix_interaction_requests_interaction_id"),
        "interaction_requests",
        ["interaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_requests_requested_by"),
        "interaction_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        "uq_interaction_requests_pending",
        "interaction_requests",
        ["interaction_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.add_column(
        "stages", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "uq_transitions_active_edge",
        "workflow_transitions",
        ["workflow_id", "from_stage_id", "to_stage_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "uq_transitions_one_start",
        "workflow_transitions",
        ["workflow_id"],
        unique=True,
        postgresql_where=sa.text("from_stage_id IS NULL AND is_active"),
    )
    # ### end Alembic commands ###
    # CHECK на существующей таблице автогенерация не видит
    op.create_check_constraint(
        "chk_transition_no_loop",
        "workflow_transitions",
        "from_stage_id IS DISTINCT FROM to_stage_id",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("chk_transition_no_loop", "workflow_transitions", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_transitions_one_start",
        table_name="workflow_transitions",
        postgresql_where=sa.text("from_stage_id IS NULL AND is_active"),
    )
    op.drop_index(
        "uq_transitions_active_edge",
        table_name="workflow_transitions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_column("stages", "archived_at")
    op.drop_index(
        "uq_interaction_requests_pending",
        table_name="interaction_requests",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        op.f("ix_interaction_requests_requested_by"), table_name="interaction_requests"
    )
    op.drop_index(
        op.f("ix_interaction_requests_interaction_id"),
        table_name="interaction_requests",
    )
    op.drop_table("interaction_requests")
    op.drop_index(
        "uq_documents_replaces",
        table_name="interaction_documents",
        postgresql_where=sa.text("replaces_document_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_interaction_documents_interaction_id"),
        table_name="interaction_documents",
    )
    op.drop_table("interaction_documents")
    # ### end Alembic commands ###
