"""comments on interaction places

Revision ID: 335bc12c61ff
Revises: 092e8988e5c7
Create Date: 2026-09-29 06:50:25.269038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335bc12c61ff'
down_revision: Union[str, Sequence[str], None] = '092e8988e5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('side_pointer_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('branch_id IS NULL OR side_pointer_id IS NULL', name=op.f('chk_comment_place')),
    sa.CheckConstraint('deleted_by IS NULL OR deleted_at IS NOT NULL', name=op.f('chk_comment_deleted_by')),
    sa.CheckConstraint('length(btrim(text)) BETWEEN 1 AND 4000', name=op.f('chk_comment_text')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_comments_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_comments_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_comments_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['comments.id'], name=op.f('fk_comments_reply_to_id_comments'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['side_pointer_id'], ['side_pointers.id'], name=op.f('fk_comments_side_pointer_id_side_pointers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_comments_stage_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_interaction', 'comments', ['interaction_id', 'id'], unique=False)
    op.create_index('ix_comments_reply_to', 'comments', ['reply_to_id'], unique=False)
    op.create_table('comment_attachments',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_comment_attachments_attachment_id_attachments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_comment_attachments_comment_id_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'attachment_id', name=op.f('pk_comment_attachments')),
    sa.UniqueConstraint('attachment_id', name=op.f('uq_comment_attachments_attachment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_attachments')
    op.drop_index('ix_comments_reply_to', table_name='comments')
    op.drop_index('ix_comments_interaction', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
