"""initial schema with org structure and sessions

Revision ID: 3e49f0777eb2
Revises:
Create Date: 2026-09-22 22:57:08.079641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e49f0777eb2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("preview", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(
        op.f("ix_attachments_storage_key"), "attachments", ["storage_key"], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("target_type", sa.String(length=30), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(actor_type = 'SYSTEM' AND actor_id IS NULL) OR (actor_type = 'USER' AND actor_id IS NOT NULL)",
            name=op.f("chk_audit_actor_invariants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_type"), "audit_logs", ["actor_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_target_id"), "audit_logs", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_target_type"), "audit_logs", ["target_type"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "universities",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contacts", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
    )
    op.create_index(op.f("ix_universities_name"), "universities", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("manager", "superviser", "admin", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "role_transition_status",
            sa.String(length=20),
            server_default="NONE",
            nullable=False,
        ),
        sa.Column(
            "identity_sync_status",
            sa.String(length=50),
            server_default="OK",
            nullable=False,
        ),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "identity_sync_status IN ('OK', 'ROLE_MAPPING_CONFLICT')",
            name=op.f("chk_user_identity_sync_status"),
        ),
        sa.CheckConstraint(
            "role_transition_status IN ('NONE', 'PENDING')",
            name=op.f("chk_user_role_transition_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("ix_users_identity_sync_status"),
        "users",
        ["identity_sync_status"],
        unique=False,
    )
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(
        op.f("ix_users_role_transition_status"),
        "users",
        ["role_transition_status"],
        unique=False,
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "vendors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contacts", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=True)
    op.create_table(
        "workflows",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
    )
    op.create_index(
        op.f("ix_workflows_is_published"), "workflows", ["is_published"], unique=False
    )
    op.create_index(op.f("ix_workflows_name"), "workflows", ["name"], unique=True)
    op.create_table(
        "admins",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["users.id"], name=op.f("fk_admins_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
    )
    op.create_table(
        "pending_org_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("origin_supervisor_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=30), server_default="PENDING", nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "action_type IN ('OFFBOARDING_MANAGER', 'OFFBOARDING_SUPERVISER', 'ROLE_TRANSITION')",
            name=op.f("chk_pending_org_action_type"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED')",
            name=op.f("chk_pending_org_action_status"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_supervisor_id"],
            ["users.id"],
            name=op.f("fk_pending_org_actions_origin_supervisor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
            name=op.f("fk_pending_org_actions_target_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_org_actions")),
    )
    op.create_index(
        op.f("ix_pending_org_actions_action_type"),
        "pending_org_actions",
        ["action_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_created_at"),
        "pending_org_actions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_lease_until"),
        "pending_org_actions",
        ["lease_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_next_retry_at"),
        "pending_org_actions",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_origin_supervisor_id"),
        "pending_org_actions",
        ["origin_supervisor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_status"),
        "pending_org_actions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_target_id"),
        "pending_org_actions",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_org_actions_worker_id"),
        "pending_org_actions",
        ["worker_id"],
        unique=False,
    )
    op.create_index(
        "uq_active_pending_org_action",
        "pending_org_actions",
        ["action_type", "target_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'IN_PROGRESS')"),
    )
    op.create_table(
        "stages",
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "consumes_capacity", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_terminal = TRUE AND consumes_capacity = TRUE)",
            name=op.f("chk_stage_terminal_no_capacity"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_stages_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stages")),
        sa.UniqueConstraint("id", "workflow_id", name="uq_stages_id_workflow_id"),
    )
    op.create_index(
        op.f("ix_stages_consumes_capacity"),
        "stages",
        ["consumes_capacity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stages_is_terminal"), "stages", ["is_terminal"], unique=False
    )
    op.create_index(
        op.f("ix_stages_workflow_id"), "stages", ["workflow_id"], unique=False
    )
    op.create_table(
        "supervisers",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("max_subordinates", sa.Integer(), server_default="5", nullable=False),
        sa.CheckConstraint(
            "max_subordinates BETWEEN 1 AND 50",
            name=op.f("chk_superviser_max_subordinates"),
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
            name=op.f("fk_supervisers_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisers")),
    )
    op.create_table(
        "managers",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("superviser_id", sa.String(length=255), nullable=True),
        sa.Column(
            "manual_workload_status",
            sa.String(length=50),
            server_default="available",
            nullable=False,
        ),
        sa.Column(
            "max_active_projects", sa.Integer(), server_default="5", nullable=False
        ),
        sa.CheckConstraint(
            "manual_workload_status IN ('available', 'unavailable')",
            name=op.f("chk_manager_manual_workload_status"),
        ),
        sa.CheckConstraint(
            "max_active_projects BETWEEN 1 AND 50",
            name=op.f("chk_manager_max_active_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["users.id"], name=op.f("fk_managers_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["superviser_id"],
            ["supervisers.id"],
            name=op.f("fk_managers_superviser_id_supervisers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_managers")),
    )
    op.create_index(
        op.f("ix_managers_manual_workload_status"),
        "managers",
        ["manual_workload_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_managers_superviser_id"), "managers", ["superviser_id"], unique=False
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column("from_stage_id", sa.Integer(), nullable=True),
        sa.Column("to_stage_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("required_actions", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["stages.id"],
            name=op.f("fk_workflow_transitions_from_stage_id_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["stages.id"],
            name=op.f("fk_workflow_transitions_to_stage_id_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_transitions_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_transitions")),
    )
    op.create_index(
        op.f("ix_workflow_transitions_from_stage_id"),
        "workflow_transitions",
        ["from_stage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transitions_to_stage_id"),
        "workflow_transitions",
        ["to_stage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_transitions_workflow_id"),
        "workflow_transitions",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "interactions",
        sa.Column("university_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("it_program", sa.String(length=255), nullable=True),
        sa.Column("it_product", sa.String(length=255), nullable=True),
        sa.Column("workflow_id", sa.Integer(), nullable=True),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("last_owner_id", sa.String(length=255), nullable=True),
        sa.Column("is_paused", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "pause_state", sa.String(length=30), server_default="ACTIVE", nullable=False
        ),
        sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(pause_state = 'ACTIVE' AND is_paused = FALSE AND paused_until IS NULL) OR (pause_state = 'PAUSED_MANUAL' AND is_paused = TRUE AND paused_until IS NULL) OR (pause_state = 'PAUSED_TIMED' AND is_paused = TRUE AND paused_until IS NOT NULL) OR (pause_state = 'EXPIRED_WAITING_CAPACITY' AND is_paused = TRUE AND paused_until IS NULL)",
            name=op.f("chk_interaction_pause_state"),
        ),
        sa.CheckConstraint(
            "state_id IS NULL OR workflow_id IS NOT NULL",
            name=op.f("chk_interaction_stage_requires_workflow"),
        ),
        sa.ForeignKeyConstraint(
            ["last_owner_id"],
            ["users.id"],
            name=op.f("fk_interactions_last_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["managers.id"],
            name=op.f("fk_interactions_owner_id_managers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["state_id", "workflow_id"],
            ["stages.id", "stages.workflow_id"],
            name="fk_interactions_state_id_workflow_id_stages",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_interactions_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_interactions_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_interactions_workflow_id_workflows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interactions")),
    )
    op.create_index(
        op.f("ix_interactions_is_paused"), "interactions", ["is_paused"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_last_owner_id"),
        "interactions",
        ["last_owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interactions_owner_id"), "interactions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_pause_state"),
        "interactions",
        ["pause_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interactions_paused_until"),
        "interactions",
        ["paused_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interactions_state_id"), "interactions", ["state_id"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_university_id"),
        "interactions",
        ["university_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interactions_vendor_id"), "interactions", ["vendor_id"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_workflow_id"),
        "interactions",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "transition_attachments",
        sa.Column("transition_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["attachments.id"],
            name=op.f("fk_transition_attachments_attachment_id_attachments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["workflow_transitions.id"],
            name=op.f("fk_transition_attachments_transition_id_workflow_transitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "transition_id", "attachment_id", name=op.f("pk_transition_attachments")
        ),
    )
    op.create_index(
        op.f("ix_transition_attachments_attachment_id"),
        "transition_attachments",
        ["attachment_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Часть обновлений идёт прямым SQL мимо ORM-хука onupdate, поэтому метку
    # времени проставляет сама СУБД
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = clock_timestamp();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    """)

    # Журнал аудита только на добавление: правки и зачистка запрещены на уровне СУБД
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_logs_append_only_guard()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs table is append-only. UPDATE, DELETE and TRUNCATE operations are strictly forbidden.';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_logs_append_only_guard
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only_guard();
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_logs_truncate_guard
        BEFORE TRUNCATE ON audit_logs
        FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_append_only_guard();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_truncate_guard ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only_guard ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS audit_logs_append_only_guard()")
    op.execute("DROP TRIGGER IF EXISTS trg_users_updated_at ON users")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transition_attachments_attachment_id"),
        table_name="transition_attachments",
    )
    op.drop_table("transition_attachments")
    op.drop_index(op.f("ix_interactions_workflow_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_vendor_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_university_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_state_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_paused_until"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_pause_state"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_owner_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_last_owner_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_is_paused"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(
        op.f("ix_workflow_transitions_workflow_id"), table_name="workflow_transitions"
    )
    op.drop_index(
        op.f("ix_workflow_transitions_to_stage_id"), table_name="workflow_transitions"
    )
    op.drop_index(
        op.f("ix_workflow_transitions_from_stage_id"), table_name="workflow_transitions"
    )
    op.drop_table("workflow_transitions")
    op.drop_index(op.f("ix_managers_superviser_id"), table_name="managers")
    op.drop_index(op.f("ix_managers_manual_workload_status"), table_name="managers")
    op.drop_table("managers")
    op.drop_table("supervisers")
    op.drop_index(op.f("ix_stages_workflow_id"), table_name="stages")
    op.drop_index(op.f("ix_stages_is_terminal"), table_name="stages")
    op.drop_index(op.f("ix_stages_consumes_capacity"), table_name="stages")
    op.drop_table("stages")
    op.drop_index(
        "uq_active_pending_org_action",
        table_name="pending_org_actions",
        postgresql_where=sa.text("status IN ('PENDING', 'IN_PROGRESS')"),
    )
    op.drop_index(
        op.f("ix_pending_org_actions_worker_id"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_target_id"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_status"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_origin_supervisor_id"),
        table_name="pending_org_actions",
    )
    op.drop_index(
        op.f("ix_pending_org_actions_next_retry_at"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_lease_until"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_created_at"), table_name="pending_org_actions"
    )
    op.drop_index(
        op.f("ix_pending_org_actions_action_type"), table_name="pending_org_actions"
    )
    op.drop_table("pending_org_actions")
    op.drop_table("admins")
    op.drop_index(op.f("ix_workflows_name"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_is_published"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role_transition_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_identity_sync_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_universities_name"), table_name="universities")
    op.drop_table("universities")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_audit_logs_target_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_target_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_attachments_storage_key"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###

    # drop_table не снимает тип enum, созданный вместе с users
    op.execute("DROP TYPE IF EXISTS userrole")
