"""interaction stage and assignment history

Revision ID: 454591147c79
Revises: 486918154634
Create Date: 2026-09-24 18:30:37.443467

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "454591147c79"
down_revision: str | Sequence[str] | None = "486918154634"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction_assignments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("manager_id", sa.String(length=255), nullable=True),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_interaction_assignments_interaction_id_interactions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
            name=op.f("fk_interaction_assignments_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_assignments")),
    )
    op.create_index(
        op.f("ix_interaction_assignments_interaction_id"),
        "interaction_assignments",
        ["interaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_assignments_manager_id"),
        "interaction_assignments",
        ["manager_id"],
        unique=False,
    )
    op.create_index(
        "uq_interaction_assignments_open",
        "interaction_assignments",
        ["interaction_id"],
        unique=True,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "interaction_stage_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("from_stage_id", sa.Integer(), nullable=True),
        sa.Column("to_stage_id", sa.Integer(), nullable=False),
        sa.Column("transition_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('TRANSITION', 'CLOSE', 'REOPEN', 'RELOCATION')",
            name=op.f("chk_stage_history_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_interaction_stage_history_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["stages.id"],
            name=op.f("fk_interaction_stage_history_from_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
            name=op.f("fk_interaction_stage_history_interaction_id_interactions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["stages.id"],
            name=op.f("fk_interaction_stage_history_to_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["workflow_transitions.id"],
            name=op.f(
                "fk_interaction_stage_history_transition_id_workflow_transitions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_stage_history")),
    )
    op.create_index(
        "ix_stage_history_interaction_created",
        "interaction_stage_history",
        ["interaction_id", "created_at"],
        unique=False,
    )
    op.add_column("interactions", sa.Column("pause_comment", sa.Text(), nullable=True))
    op.drop_column("interactions", "history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions",
        sa.Column(
            "history",
            postgresql.JSON(astext_type=sa.Text()),
            # у существующих заявок значения нет - без него откат упадёт
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
    )
    op.drop_column("interactions", "pause_comment")
    op.drop_index(
        "ix_stage_history_interaction_created", table_name="interaction_stage_history"
    )
    op.drop_table("interaction_stage_history")
    op.drop_index(
        "uq_interaction_assignments_open",
        table_name="interaction_assignments",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_interaction_assignments_manager_id"),
        table_name="interaction_assignments",
    )
    op.drop_index(
        op.f("ix_interaction_assignments_interaction_id"),
        table_name="interaction_assignments",
    )
    op.drop_table("interaction_assignments")
    # ### end Alembic commands ###
