"""close reasons, reasons on closing, wider stage history

Revision ID: 4bc9989d204c
Revises: 23c2a2979af2
Create Date: 2026-09-27 18:28:28.811336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc9989d204c'
down_revision: Union[str, Sequence[str], None] = '23c2a2979af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


REASONS = [
    # (код, подпись, уровень, итог, нужен комментарий) - О 4, Т-2
    ("UNIVERSITY_REFUSED", "Вуз отказался", "INTERACTION_BEFORE_SIGNING", "REFUSED", False),
    ("NO_CONTACT", "Не удалось связаться", "INTERACTION_BEFORE_SIGNING", "REFUSED", False),
    ("PRODUCTS_UNFIT", "Продукты не подошли", "INTERACTION_BEFORE_SIGNING", "REFUSED", False),
    ("NO_BUDGET", "Нет бюджета или сроков у вуза", "INTERACTION_BEFORE_SIGNING", "REFUSED", False),
    ("DUPLICATE", "Дубль заявки", "INTERACTION_BEFORE_SIGNING", "REFUSED", False),
    ("OTHER_BEFORE_SIGNING", "Другое", "INTERACTION_BEFORE_SIGNING", "REFUSED", True),
    ("ALL_BRANCHES_CLOSED", "Все ветки закрыты", "INTERACTION_AFTER_SIGNING", "DONE", False),
    ("CONTRACT_EXPIRED", "Договор истёк", "INTERACTION_AFTER_SIGNING", "DONE", False),
    ("STOPPED_USING", "Вуз перестал использовать продукт", "BRANCH", "REFUSED", False),
    ("EXCLUDED_BY_AGREEMENT", "Исключена допсоглашением", "BRANCH", "REFUSED", False),
    ("NOT_IMPLEMENTED", "Технически не внедрили", "BRANCH", "REFUSED", False),
    ("OTHER_BRANCH", "Другое", "BRANCH", "REFUSED", True),
    ("LICENSE_EXPIRED", "Лицензия истекла и не продлена", "BRANCH", "DONE", False),
    ("COMPLETED", "Завершено стандартно", "BRANCH", "DONE", False),
]
# на эти коды опирается сама система
SYSTEM_REASONS = {"EXCLUDED_BY_AGREEMENT"}
HISTORY_KINDS = (
    "TRANSITION", "CLOSE", "REOPEN", "RELOCATION", "REJECTION", "ROLLBACK",
    "CANCEL", "PAUSE", "UNPAUSE", "BRANCH_ADDED", "BRANCH_REMOVED", "SA_OPENED",
    "SA_APPROVED", "SA_REJECTED", "LICENSE_EXTENDED", "CONTRACT_EXTENDED",
    "IMPORT", "COMMENT",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('close_reasons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('needs_comment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('INTERACTION_BEFORE_SIGNING', 'INTERACTION_AFTER_SIGNING', 'BRANCH')", name=op.f('chk_close_reason_level')),
    sa.CheckConstraint("outcome IN ('DONE', 'REFUSED')", name=op.f('chk_close_reason_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_close_reasons')),
    sa.UniqueConstraint('code', name=op.f('uq_close_reasons_code'))
    )
    reasons = sa.table(
        "close_reasons",
        sa.column("code", sa.String),
        sa.column("label", sa.String),
        sa.column("level", sa.String),
        sa.column("outcome", sa.String),
        sa.column("needs_comment", sa.Boolean),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        reasons,
        [
            {
                "code": code,
                "label": label,
                "level": level,
                "outcome": outcome,
                "needs_comment": needs_comment,
                "is_system": code in SYSTEM_REASONS,
            }
            for code, label, level, outcome, needs_comment in REASONS
        ],
    )
    op.add_column('branches', sa.Column('close_reason_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_branches_close_reason_id_close_reasons'), 'branches', 'close_reasons', ['close_reason_id'], ['id'], ondelete='RESTRICT')
    op.add_column('interaction_requests', sa.Column('close_reason_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_requests_close_reason_id_close_reasons'), 'interaction_requests', 'close_reasons', ['close_reason_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('interaction_stage_history', 'to_stage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interaction_stage_history', 'kind',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.add_column('interactions', sa.Column('close_reason_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_interactions_close_reason_id_close_reasons'), 'interactions', 'close_reasons', ['close_reason_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint("chk_stage_history_kind", "interaction_stage_history", type_="check")
    op.create_check_constraint(
        "chk_stage_history_kind",
        "interaction_stage_history",
        "kind IN (" + ", ".join(f"'{k}'" for k in HISTORY_KINDS) + ")",
    )
    op.drop_constraint("chk_request_close_target", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_close_target",
        "interaction_requests",
        "kind <> 'CLOSE' OR (target_manager_id IS NULL "
        "AND close_reason_id IS NOT NULL "
        "AND (branch_id IS NULL) = (target_stage_id IS NOT NULL))",
    )
    op.drop_constraint("chk_request_branch_only_transition", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_branch_only_transition",
        "interaction_requests",
        "branch_id IS NULL OR kind IN ('TRANSITION', 'CLOSE')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_request_branch_only_transition", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_branch_only_transition",
        "interaction_requests",
        "branch_id IS NULL OR kind = 'TRANSITION'",
    )
    op.drop_constraint("chk_request_close_target", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_close_target",
        "interaction_requests",
        "kind <> 'CLOSE' OR (target_stage_id IS NOT NULL AND target_manager_id IS NULL)",
    )
    op.drop_constraint("chk_stage_history_kind", "interaction_stage_history", type_="check")
    op.create_check_constraint(
        "chk_stage_history_kind",
        "interaction_stage_history",
        "kind IN ('TRANSITION', 'CLOSE', 'REOPEN', 'RELOCATION', 'REJECTION', 'ROLLBACK')",
    )
    op.drop_constraint(op.f('fk_interactions_close_reason_id_close_reasons'), 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'close_reason_id')
    op.alter_column('interaction_stage_history', 'kind',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('interaction_stage_history', 'to_stage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_interaction_requests_close_reason_id_close_reasons'), 'interaction_requests', type_='foreignkey')
    op.drop_column('interaction_requests', 'close_reason_id')
    op.drop_constraint(op.f('fk_branches_close_reason_id_close_reasons'), 'branches', type_='foreignkey')
    op.drop_column('branches', 'close_reason_id')
    op.drop_table('close_reasons')
    # ### end Alembic commands ###
