"""pending edits of passed step values

Revision ID: 51cb572e61c8
Revises: c2ceaf91d99e
Create Date: 2026-09-25 21:53:51.182301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51cb572e61c8'
down_revision: Union[str, Sequence[str], None] = 'c2ceaf91d99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_stage_values', sa.Column('pending_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interaction_stage_values', sa.Column('pending_by', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_stage_values_pending_by_users'), 'interaction_stage_values', 'users', ['pending_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_interaction_stage_values_pending_by_users'), 'interaction_stage_values', type_='foreignkey')
    op.drop_column('interaction_stage_values', 'pending_by')
    op.drop_column('interaction_stage_values', 'pending_values')
    # ### end Alembic commands ###
