"""branch step approvals

Revision ID: 52236b0eb712
Revises: ab78cb45c0d4
Create Date: 2026-09-25 22:13:42.592506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52236b0eb712'
down_revision: Union[str, Sequence[str], None] = 'ab78cb45c0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_interaction_requests_pending'), table_name='interaction_requests', postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index('uq_interaction_requests_pending', 'interaction_requests', ['interaction_id', 'kind', 'branch_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"), postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("chk_request_branch_only_transition"),
        "interaction_requests",
        "branch_id IS NULL OR kind = 'TRANSITION'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("chk_request_branch_only_transition"), "interaction_requests", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_interaction_requests_pending', table_name='interaction_requests', postgresql_where=sa.text("status = 'PENDING'"), postgresql_nulls_not_distinct=True)
    op.create_index(op.f('uq_interaction_requests_pending'), 'interaction_requests', ['interaction_id', 'kind'], unique=True, postgresql_where="((status)::text = 'PENDING'::text)")
    # ### end Alembic commands ###
