"""report exports queue

Revision ID: 57ea0170aa1e
Revises: ba9d7907a823
Create Date: 2026-09-28 14:50:28.907723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ea0170aa1e'
down_revision: Union[str, Sequence[str], None] = 'ba9d7907a823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_exports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='QUEUED', nullable=False),
    sa.Column('error_code', sa.String(length=10), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'RUNNING') = (lease_until IS NOT NULL AND worker_id IS NOT NULL)", name=op.f('chk_report_export_running')),
    sa.CheckConstraint("(status IN ('DONE', 'EXPIRED')) = (storage_key IS NOT NULL)", name=op.f('chk_report_export_done')),
    sa.CheckConstraint("(status IN ('FAILED', 'TIMED_OUT')) = (error_code IS NOT NULL)", name=op.f('chk_report_export_error')),
    sa.CheckConstraint("format IN ('xlsx', 'xls', 'pdf')", name=op.f('chk_report_export_format')),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'TIMED_OUT', 'EXPIRED')", name=op.f('chk_report_export_status')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_report_exports_requested_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_index(op.f('ix_report_exports_created_at'), 'report_exports', ['created_at'], unique=False)
    op.create_index('ix_report_exports_queue', 'report_exports', ['status', 'id'], unique=False)
    op.create_index(op.f('ix_report_exports_requested_by'), 'report_exports', ['requested_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_exports_requested_by'), table_name='report_exports')
    op.drop_index('ix_report_exports_queue', table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_created_at'), table_name='report_exports')
    op.drop_table('report_exports')
    # ### end Alembic commands ###
