"""documents on passed steps wait for approval

Revision ID: 6245b9b84967
Revises: c9bbef5ebb8b
Create Date: 2026-09-25 21:35:28.770731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6245b9b84967'
down_revision: Union[str, Sequence[str], None] = 'c9bbef5ebb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_documents', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("chk_document_status"),
        "interaction_documents",
        "status IN ('ACTIVE', 'PENDING', 'REJECTED')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("chk_document_status"), "interaction_documents", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_documents', 'status')
    # ### end Alembic commands ###
