"""document title, kind and metadata

Revision ID: 7165274f3290
Revises: 261270c7dde5
Create Date: 2026-09-25 18:02:34.716486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7165274f3290"
down_revision: str | Sequence[str] | None = "261270c7dde5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # сначала пустое, потом из имени файла - иначе упадёт на базе с документами
    op.add_column(
        "interaction_documents",
        sa.Column("title", sa.String(length=255), nullable=True),
    )
    op.execute(
        "UPDATE interaction_documents d SET title = a.filename "
        "FROM attachments a WHERE a.id = d.attachment_id"
    )
    op.alter_column("interaction_documents", "title", nullable=False)
    op.add_column(
        "interaction_documents", sa.Column("kind", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "interaction_documents",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_interaction_documents_kind"),
        "interaction_documents",
        ["kind"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interaction_documents_kind"), table_name="interaction_documents"
    )
    op.drop_column("interaction_documents", "metadata")
    op.drop_column("interaction_documents", "kind")
    op.drop_column("interaction_documents", "title")
    # ### end Alembic commands ###
