"""contract signed flag separate from the point of no return, contract number optional

Revision ID: 79b9e3f52fea
Revises: 7ded11a931f8
Create Date: 2026-09-27 23:17:01.589620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b9e3f52fea'
down_revision: Union[str, Sequence[str], None] = '7ded11a931f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('no_return_at', sa.DateTime(timezone=True), nullable=True))
    # номер договора необязателен (Д13)
    op.drop_constraint("chk_document_contract_number", "interaction_documents", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "chk_document_contract_number",
        "interaction_documents",
        "kind <> 'CONTRACT' OR contract_number IS NOT NULL",
    )
    op.drop_column('interactions', 'no_return_at')
    # ### end Alembic commands ###
