"""branches: program and at most one product

Revision ID: 8503cc10d677
Revises: fb8ad264cb0f
Create Date: 2026-09-27 17:47:27.960808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8503cc10d677'
down_revision: Union[str, Sequence[str], None] = 'fb8ad264cb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.String(length=20), server_default='PROPOSED', nullable=False),
    sa.Column('origin', sa.String(length=30), server_default='CONTRACT', nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_signed_at', sa.Date(), nullable=True),
    sa.Column('license_term_years', sa.Integer(), nullable=True),
    sa.Column('license_until', sa.Date(), nullable=True),
    sa.Column('transfer_status', sa.String(length=20), server_default='NOT_TRANSFERRED', nullable=False),
    sa.Column('teachers_trained', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contract_status IN ('PROPOSED', 'APPROVED', 'REJECTED')", name=op.f('chk_branch_contract_status')),
    sa.CheckConstraint("state_id IS NULL OR contract_status = 'APPROVED'", name=op.f('chk_branch_on_stage_is_approved')),
    sa.CheckConstraint("transfer_status IN ('NOT_TRANSFERRED', 'TRANSFERRED')", name=op.f('chk_branch_transfer_status')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_branches_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_branches_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_branches_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['it_programs.id'], name=op.f('fk_branches_program_id_it_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['stages.id'], name=op.f('fk_branches_state_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_interaction_id'), 'branches', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_branches_product_id'), 'branches', ['product_id'], unique=False)
    op.create_index(op.f('ix_branches_program_id'), 'branches', ['program_id'], unique=False)
    op.create_index(op.f('ix_branches_state_id'), 'branches', ['state_id'], unique=False)
    op.create_index('uq_branches_interaction_program_product', 'branches', ['interaction_id', 'program_id', 'product_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('fk_interaction_documents_branch_id_interaction_branches'), 'interaction_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_documents_branch_id_branches'), 'interaction_documents', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_requests_branch_id_interaction_branches'), 'interaction_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_requests_branch_id_branches'), 'interaction_requests', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_stage_history_branch_id_interaction_branches'), 'interaction_stage_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_stage_history_branch_id_branches'), 'interaction_stage_history', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_stage_values_branch_id_interaction_branches'), 'interaction_stage_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_stage_values_branch_id_branches'), 'interaction_stage_values', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_interaction_branches_interaction_id'), table_name='interaction_branches')
    op.drop_index(op.f('ix_interaction_branches_state_id'), table_name='interaction_branches')
    op.drop_table('interaction_branches')
    op.drop_index(op.f('ix_interaction_products_interaction_id'), table_name='interaction_products')
    op.drop_index(op.f('ix_interaction_products_product_id'), table_name='interaction_products')
    op.drop_table('interaction_products')
    op.drop_index(op.f('ix_interactions_vendor_id'), table_name='interactions')
    op.drop_constraint(op.f('fk_interactions_vendor_id_vendors'), 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'it_product')
    op.drop_column('interactions', 'it_program')
    op.drop_column('interactions', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interactions', sa.Column('it_program', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('interactions', sa.Column('it_product', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_interactions_vendor_id_vendors'), 'interactions', 'vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_interactions_vendor_id'), 'interactions', ['vendor_id'], unique=False)
    op.create_table('interaction_products',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PROPOSED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['PROPOSED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]::text[])", name=op.f('chk_interaction_product_status')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_interaction_products_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_products_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_interaction_products_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_products')),
    sa.UniqueConstraint('interaction_id', 'product_id', name=op.f('uq_interaction_products'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_interaction_products_product_id'), 'interaction_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_interaction_products_interaction_id'), 'interaction_products', ['interaction_id'], unique=False)
    op.create_table('interaction_branches',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interaction_product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_branches_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_product_id'], ['interaction_products.id'], name=op.f('fk_interaction_branches_interaction_product_id_interact_57a9'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['stages.id'], name=op.f('fk_interaction_branches_state_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_branches')),
    sa.UniqueConstraint('interaction_product_id', name=op.f('uq_interaction_branches_interaction_product_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_interaction_branches_state_id'), 'interaction_branches', ['state_id'], unique=False)
    op.create_index(op.f('ix_interaction_branches_interaction_id'), 'interaction_branches', ['interaction_id'], unique=False)
    op.drop_constraint(op.f('fk_interaction_stage_values_branch_id_branches'), 'interaction_stage_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_stage_values_branch_id_interaction_branches'), 'interaction_stage_values', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_stage_history_branch_id_branches'), 'interaction_stage_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_stage_history_branch_id_interaction_branches'), 'interaction_stage_history', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_requests_branch_id_branches'), 'interaction_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_requests_branch_id_interaction_branches'), 'interaction_requests', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_interaction_documents_branch_id_branches'), 'interaction_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interaction_documents_branch_id_interaction_branches'), 'interaction_documents', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_branches_interaction_program_product', table_name='branches', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_branches_state_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_program_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_product_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_interaction_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
