"""catalog v1.3: it programs, product directions, specialties

Revision ID: 950a0ef5f9b3
Revises: 52236b0eb712
Create Date: 2026-09-27 13:56:24.051563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '950a0ef5f9b3'
down_revision: Union[str, Sequence[str], None] = '52236b0eb712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties')),
    sa.UniqueConstraint('code', name=op.f('uq_specialties_code'))
    )
    op.create_table('it_programs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('site_course_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['it_directions.id'], name=op.f('fk_it_programs_direction_id_it_directions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_it_programs')),
    sa.UniqueConstraint('name', name=op.f('uq_it_programs_name')),
    sa.UniqueConstraint('site_course_id', name=op.f('uq_it_programs_site_course_id'))
    )
    op.create_index(op.f('ix_it_programs_direction_id'), 'it_programs', ['direction_id'], unique=False)
    op.create_table('specialty_directions',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['it_directions.id'], name=op.f('fk_specialty_directions_direction_id_it_directions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_specialty_directions_specialty_id_specialties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialty_id', 'direction_id', name=op.f('pk_specialty_directions'))
    )
    op.create_table('university_specialties',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_university_specialties_specialty_id_specialties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_university_specialties_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('university_id', 'specialty_id', name=op.f('pk_university_specialties'))
    )
    op.create_table('product_directions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['it_directions.id'], name=op.f('fk_product_directions_direction_id_it_directions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_directions_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'direction_id', name=op.f('pk_product_directions'))
    )
    op.create_table('program_products',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_program_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['it_programs.id'], name=op.f('fk_program_products_program_id_it_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'product_id', name=op.f('pk_program_products'))
    )
    op.drop_index(op.f('ix_university_programs_university_id'), table_name='university_programs')
    op.drop_index(op.f('uq_university_programs'), table_name='university_programs', postgresql_nulls_not_distinct=True)
    op.drop_table('university_programs')
    op.add_column('products', sa.Column('url', sa.String(length=500), nullable=True))
    op.alter_column('products', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_products_direction_id'), table_name='products')
    op.drop_index(op.f('uq_products_name_vendor'), table_name='products', postgresql_nulls_not_distinct=True)
    op.create_index('uq_products_name_vendor', 'products', ['name', 'vendor_id'], unique=True)
    op.drop_constraint(op.f('fk_products_direction_id_it_directions'), 'products', type_='foreignkey')
    op.drop_column('products', 'direction_id')
    op.drop_column('products', 'keywords')
    op.drop_column('products', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('direction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_products_direction_id_it_directions'), 'products', 'it_directions', ['direction_id'], ['id'], ondelete='SET NULL')
    op.drop_index('uq_products_name_vendor', table_name='products')
    op.create_index(op.f('uq_products_name_vendor'), 'products', ['name', 'vendor_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_products_direction_id'), 'products', ['direction_id'], unique=False)
    op.alter_column('products', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('products', 'url')
    op.create_table('university_programs',
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('faculty', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('disciplines', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_university_programs_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_university_programs'))
    )
    op.create_index(op.f('uq_university_programs'), 'university_programs', ['university_id', 'code', 'name'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_university_programs_university_id'), 'university_programs', ['university_id'], unique=False)
    op.drop_table('program_products')
    op.drop_table('product_directions')
    op.drop_table('university_specialties')
    op.drop_table('specialty_directions')
    op.drop_index(op.f('ix_it_programs_direction_id'), table_name='it_programs')
    op.drop_table('it_programs')
    op.drop_table('specialties')
    # ### end Alembic commands ###
