"""supplementary agreements, parallel step, branch iterations, history payload

Revision ID: a68ba3165ea1
Revises: 0beee173885d
Create Date: 2026-09-28 08:14:59.527701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68ba3165ea1'
down_revision: Union[str, Sequence[str], None] = '0beee173885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


HISTORY_KINDS = (
    "TRANSITION", "CLOSE", "REOPEN", "RELOCATION", "REJECTION", "ROLLBACK",
    "CANCEL", "PAUSE", "UNPAUSE", "BRANCH_ADDED", "BRANCH_REMOVED", "SA_OPENED",
    "SA_APPROVED", "SA_REJECTED", "LICENSE_EXTENDED", "CONTRACT_EXTENDED",
    "IMPORT", "COMMENT", "SLOT_PASSIVE", "SLOT_ACTIVE",
)
NEW_KINDS = ("SA_CANCELLED", "SA_RETURNED", "RESTART")
CHECKS = (
    (
        "chk_stage_parallel",
        "stages",
        "NOT is_parallel OR (NOT is_branch_stage AND NOT is_terminal "
        "AND NOT is_branch_start)",
    ),
    (
        "chk_branch_origin_sa",
        "branches",
        "(origin = 'SUPPLEMENTARY_AGREEMENT') = (supplementary_agreement_id IS NOT NULL)",
    ),
    (
        "chk_document_sa_scan",
        "interaction_documents",
        "(supplementary_agreement_id IS NOT NULL) = (kind = 'SUPPLEMENTARY_AGREEMENT')",
    ),
    (
        "chk_request_sa",
        "interaction_requests",
        "(kind = 'SA_APPROVAL') = (supplementary_agreement_id IS NOT NULL) "
        "AND (kind <> 'SA_APPROVAL' OR (target_stage_id IS NULL "
        "AND target_manager_id IS NULL AND transition_id IS NULL "
        "AND branch_id IS NULL AND close_reason_id IS NULL "
        "AND branch_close_reason_id IS NULL))",
    ),
)


def _kinds(kinds):
    return "kind IN (" + ", ".join(f"'{k}'" for k in kinds) + ")"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplementary_agreements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('stall_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('APPROVED', 'REJECTED', 'CANCELLED')) = (decided_at IS NOT NULL)", name=op.f('chk_sa_decided')),
    sa.CheckConstraint("status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')", name=op.f('chk_sa_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supplementary_agreements_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_supplementary_agreements_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_supplementary_agreements_interaction_id_interactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplementary_agreements'))
    )
    op.create_index(op.f('ix_supplementary_agreements_interaction_id'), 'supplementary_agreements', ['interaction_id'], unique=False)
    op.create_index('uq_sa_open_per_interaction', 'supplementary_agreements', ['interaction_id'], unique=True, postgresql_where=sa.text("status IN ('DRAFT', 'PENDING')"))
    op.create_table('sa_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sa_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('license_until', sa.Date(), nullable=True),
    sa.Column('contract_valid_until', sa.Date(), nullable=True),
    sa.Column('result_branch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'NEW_BRANCH' AND program_id IS NOT NULL AND branch_id IS NULL AND license_until IS NULL AND contract_valid_until IS NULL) OR (type = 'EXTEND_LICENSE' AND branch_id IS NOT NULL AND license_until IS NOT NULL AND program_id IS NULL AND product_id IS NULL AND contract_valid_until IS NULL) OR (type IN ('RESUME', 'EXCLUDE') AND branch_id IS NOT NULL AND program_id IS NULL AND product_id IS NULL AND license_until IS NULL AND contract_valid_until IS NULL) OR (type = 'EXTEND_CONTRACT' AND contract_valid_until IS NOT NULL AND branch_id IS NULL AND program_id IS NULL AND product_id IS NULL AND license_until IS NULL)", name=op.f('chk_sa_action_shape')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sa_actions_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sa_actions_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['it_programs.id'], name=op.f('fk_sa_actions_program_id_it_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_branch_id'], ['branches.id'], name=op.f('fk_sa_actions_result_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sa_id'], ['supplementary_agreements.id'], name=op.f('fk_sa_actions_sa_id_supplementary_agreements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sa_actions'))
    )
    op.create_index(op.f('ix_sa_actions_sa_id'), 'sa_actions', ['sa_id'], unique=False)
    op.create_index('uq_sa_action_branch', 'sa_actions', ['sa_id', 'branch_id', 'type'], unique=True, postgresql_where=sa.text('branch_id IS NOT NULL'))
    op.create_index('uq_sa_action_contract', 'sa_actions', ['sa_id'], unique=True, postgresql_where=sa.text("type = 'EXTEND_CONTRACT'"))
    op.create_index('uq_sa_action_new_pair', 'sa_actions', ['sa_id', 'program_id', 'product_id'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text("type = 'NEW_BRANCH'"))
    op.add_column('branches', sa.Column('supplementary_agreement_id', sa.BigInteger(), nullable=True))
    op.add_column('branches', sa.Column('iteration', sa.Integer(), server_default='1', nullable=False))
    op.drop_index(op.f('uq_branches_interaction_program_product'), table_name='branches', postgresql_nulls_not_distinct=True)
    op.create_index('uq_branches_interaction_program_product', 'branches', ['interaction_id', 'program_id', 'product_id', 'iteration'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_index('uq_branches_live_pair', 'branches', ['interaction_id', 'program_id', 'product_id'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_foreign_key(op.f('fk_branches_supplementary_agreement_id_supplementary_agreements'), 'branches', 'supplementary_agreements', ['supplementary_agreement_id'], ['id'])
    op.add_column('interaction_documents', sa.Column('supplementary_agreement_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_interaction_documents_supplementary_agreement_id'), 'interaction_documents', ['supplementary_agreement_id'], unique=False)
    op.create_foreign_key(op.f('fk_interaction_documents_supplementary_agreement_id_supplementary_agreements'), 'interaction_documents', 'supplementary_agreements', ['supplementary_agreement_id'], ['id'])
    op.add_column('interaction_requests', sa.Column('supplementary_agreement_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_requests_supplementary_agreement_id_supplementary_agreements'), 'interaction_requests', 'supplementary_agreements', ['supplementary_agreement_id'], ['id'])
    op.add_column('interaction_stage_history', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('stages', sa.Column('is_parallel', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('uq_stages_one_parallel', 'stages', ['workflow_id'], unique=True, postgresql_where=sa.text('is_parallel AND archived_at IS NULL'))
    for name, table, condition in CHECKS:
        op.create_check_constraint(name, table, condition)
    op.drop_constraint("chk_request_kind", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_kind",
        "interaction_requests",
        "kind IN ('TRANSFER', 'CLOSE', 'TRANSITION', 'SA_APPROVAL')",
    )
    op.drop_constraint("chk_stage_history_kind", "interaction_stage_history", type_="check")
    op.create_check_constraint(
        "chk_stage_history_kind", "interaction_stage_history", _kinds(HISTORY_KINDS + NEW_KINDS)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_stage_history_kind", "interaction_stage_history", type_="check")
    op.create_check_constraint(
        "chk_stage_history_kind", "interaction_stage_history", _kinds(HISTORY_KINDS)
    )
    op.drop_constraint("chk_request_kind", "interaction_requests", type_="check")
    op.create_check_constraint(
        "chk_request_kind", "interaction_requests", "kind IN ('TRANSFER', 'CLOSE', 'TRANSITION')"
    )
    for name, table, _ in CHECKS:
        op.drop_constraint(name, table, type_="check")
    op.drop_index('uq_stages_one_parallel', table_name='stages', postgresql_where=sa.text('is_parallel AND archived_at IS NULL'))
    op.drop_column('stages', 'is_parallel')
    op.drop_column('interaction_stage_history', 'payload')
    op.drop_constraint(op.f('fk_interaction_requests_supplementary_agreement_id_supplementary_agreements'), 'interaction_requests', type_='foreignkey')
    op.drop_column('interaction_requests', 'supplementary_agreement_id')
    op.drop_constraint(op.f('fk_interaction_documents_supplementary_agreement_id_supplementary_agreements'), 'interaction_documents', type_='foreignkey')
    op.drop_index(op.f('ix_interaction_documents_supplementary_agreement_id'), table_name='interaction_documents')
    op.drop_column('interaction_documents', 'supplementary_agreement_id')
    op.drop_constraint(op.f('fk_branches_supplementary_agreement_id_supplementary_agreements'), 'branches', type_='foreignkey')
    op.drop_index('uq_branches_live_pair', table_name='branches', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_index('uq_branches_interaction_program_product', table_name='branches', postgresql_nulls_not_distinct=True)
    op.create_index(op.f('uq_branches_interaction_program_product'), 'branches', ['interaction_id', 'program_id', 'product_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.drop_column('branches', 'iteration')
    op.drop_column('branches', 'supplementary_agreement_id')
    op.drop_index('uq_sa_action_new_pair', table_name='sa_actions', postgresql_nulls_not_distinct=True, postgresql_where=sa.text("type = 'NEW_BRANCH'"))
    op.drop_index('uq_sa_action_contract', table_name='sa_actions', postgresql_where=sa.text("type = 'EXTEND_CONTRACT'"))
    op.drop_index('uq_sa_action_branch', table_name='sa_actions', postgresql_where=sa.text('branch_id IS NOT NULL'))
    op.drop_index(op.f('ix_sa_actions_sa_id'), table_name='sa_actions')
    op.drop_table('sa_actions')
    op.drop_index('uq_sa_open_per_interaction', table_name='supplementary_agreements', postgresql_where=sa.text("status IN ('DRAFT', 'PENDING')"))
    op.drop_index(op.f('ix_supplementary_agreements_interaction_id'), table_name='supplementary_agreements')
    op.drop_table('supplementary_agreements')
    # ### end Alembic commands ###
