"""contract products and product branches

Revision ID: ab78cb45c0d4
Revises: 1eddb3e90f0f
Create Date: 2026-09-25 22:06:12.311682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab78cb45c0d4'
down_revision: Union[str, Sequence[str], None] = '1eddb3e90f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PROPOSED', nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'APPROVED', 'REJECTED')", name=op.f('chk_interaction_product_status')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_interaction_products_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_products_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_interaction_products_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_products')),
    sa.UniqueConstraint('interaction_id', 'product_id', name='uq_interaction_products')
    )
    op.create_index(op.f('ix_interaction_products_interaction_id'), 'interaction_products', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_interaction_products_product_id'), 'interaction_products', ['product_id'], unique=False)
    op.create_table('interaction_branches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('interaction_product_id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_branches_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_product_id'], ['interaction_products.id'], name=op.f('fk_interaction_branches_interaction_product_id_interaction_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['state_id'], ['stages.id'], name=op.f('fk_interaction_branches_state_id_stages'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_branches')),
    sa.UniqueConstraint('interaction_product_id', name=op.f('uq_interaction_branches_interaction_product_id'))
    )
    op.create_index(op.f('ix_interaction_branches_interaction_id'), 'interaction_branches', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_interaction_branches_state_id'), 'interaction_branches', ['state_id'], unique=False)
    op.add_column('interaction_documents', sa.Column('branch_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_documents_branch_id_interaction_branches'), 'interaction_documents', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('interaction_requests', sa.Column('branch_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_requests_branch_id_interaction_branches'), 'interaction_requests', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('interaction_stage_history', sa.Column('branch_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_interaction_stage_history_branch_id'), 'interaction_stage_history', ['branch_id'], unique=False)
    op.create_foreign_key(op.f('fk_interaction_stage_history_branch_id_interaction_branches'), 'interaction_stage_history', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('interaction_stage_values', sa.Column('branch_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('uq_stage_values_interaction_stage'), 'interaction_stage_values', type_='unique')
    op.create_index('uq_stage_values_interaction_stage_branch', 'interaction_stage_values', ['interaction_id', 'stage_id', 'branch_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_foreign_key(op.f('fk_interaction_stage_values_branch_id_interaction_branches'), 'interaction_stage_values', 'interaction_branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('stages', sa.Column('is_branch_stage', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stages', sa.Column('is_branch_start', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('uq_stages_one_branch_start', 'stages', ['workflow_id'], unique=True, postgresql_where=sa.text('is_branch_start AND archived_at IS NULL'))
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("chk_stage_branch_start"), "stages", "NOT is_branch_start OR is_branch_stage"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("chk_stage_branch_start"), "stages", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stages_one_branch_start', table_name='stages', postgresql_where=sa.text('is_branch_start AND archived_at IS NULL'))
    op.drop_column('stages', 'is_branch_start')
    op.drop_column('stages', 'is_branch_stage')
    op.drop_constraint(op.f('fk_interaction_stage_values_branch_id_interaction_branches'), 'interaction_stage_values', type_='foreignkey')
    op.drop_index('uq_stage_values_interaction_stage_branch', table_name='interaction_stage_values', postgresql_nulls_not_distinct=True)
    op.create_unique_constraint(op.f('uq_stage_values_interaction_stage'), 'interaction_stage_values', ['interaction_id', 'stage_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('interaction_stage_values', 'branch_id')
    op.drop_constraint(op.f('fk_interaction_stage_history_branch_id_interaction_branches'), 'interaction_stage_history', type_='foreignkey')
    op.drop_index(op.f('ix_interaction_stage_history_branch_id'), table_name='interaction_stage_history')
    op.drop_column('interaction_stage_history', 'branch_id')
    op.drop_constraint(op.f('fk_interaction_requests_branch_id_interaction_branches'), 'interaction_requests', type_='foreignkey')
    op.drop_column('interaction_requests', 'branch_id')
    op.drop_constraint(op.f('fk_interaction_documents_branch_id_interaction_branches'), 'interaction_documents', type_='foreignkey')
    op.drop_column('interaction_documents', 'branch_id')
    op.drop_index(op.f('ix_interaction_branches_state_id'), table_name='interaction_branches')
    op.drop_index(op.f('ix_interaction_branches_interaction_id'), table_name='interaction_branches')
    op.drop_table('interaction_branches')
    op.drop_index(op.f('ix_interaction_products_product_id'), table_name='interaction_products')
    op.drop_index(op.f('ix_interaction_products_interaction_id'), table_name='interaction_products')
    op.drop_table('interaction_products')
    # ### end Alembic commands ###
