"""workflow change requests

Revision ID: c2ceaf91d99e
Revises: 6245b9b84967
Create Date: 2026-09-25 21:38:18.017266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ceaf91d99e'
down_revision: Union[str, Sequence[str], None] = '6245b9b84967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_change_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PENDING') = (decided_at IS NULL)", name=op.f('chk_workflow_change_decided')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('chk_workflow_change_status')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_workflow_change_requests_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_workflow_change_requests_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_change_requests_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_change_requests'))
    )
    op.create_index(op.f('ix_workflow_change_requests_requested_by'), 'workflow_change_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_workflow_change_requests_status'), 'workflow_change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_change_requests_workflow_id'), 'workflow_change_requests', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_change_requests_workflow_id'), table_name='workflow_change_requests')
    op.drop_index(op.f('ix_workflow_change_requests_status'), table_name='workflow_change_requests')
    op.drop_index(op.f('ix_workflow_change_requests_requested_by'), table_name='workflow_change_requests')
    op.drop_table('workflow_change_requests')
    # ### end Alembic commands ###
