"""step rules: edge properties, stage fields and values, approval requests

Revision ID: c9bbef5ebb8b
Revises: 2e231c59583c
Create Date: 2026-09-25 21:26:10.583313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9bbef5ebb8b'
down_revision: Union[str, Sequence[str], None] = '2e231c59583c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_stage_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name=op.f('fk_interaction_stage_values_interaction_id_interactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_interaction_stage_values_stage_id_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_interaction_stage_values_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_stage_values')),
    sa.UniqueConstraint('interaction_id', 'stage_id', name='uq_stage_values_interaction_stage')
    )
    op.create_index(op.f('ix_interaction_stage_values_interaction_id'), 'interaction_stage_values', ['interaction_id'], unique=False)
    op.add_column('interaction_requests', sa.Column('transition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_interaction_requests_transition_id_workflow_transitions'), 'interaction_requests', 'workflow_transitions', ['transition_id'], ['id'], ondelete='RESTRICT')
    op.add_column('stages', sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('workflow_transitions', sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('workflow_transitions', sa.Column('reject_to_stage_id', sa.Integer(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('is_backward', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('workflow_transitions', sa.Column('is_irreversible', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('workflow_transitions', sa.Column('required_document_kinds', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_foreign_key(op.f('fk_workflow_transitions_reject_to_stage_id_stages'), 'workflow_transitions', 'stages', ['reject_to_stage_id'], ['id'], ondelete='SET NULL')
    op.drop_column('workflow_transitions', 'required_actions')
    # ### end Alembic commands ###

    # CHECK-и на существующих таблицах автогенерация не видит
    op.create_check_constraint(
        op.f("chk_transition_approval_not_on_entry"),
        "workflow_transitions",
        "NOT (requires_approval AND from_stage_id IS NULL)",
    )
    op.create_check_constraint(
        op.f("chk_transition_reject_needs_approval"),
        "workflow_transitions",
        "reject_to_stage_id IS NULL OR requires_approval",
    )
    op.drop_constraint(op.f("chk_request_kind"), "interaction_requests", type_="check")
    op.create_check_constraint(
        op.f("chk_request_kind"),
        "interaction_requests",
        "kind IN ('TRANSFER', 'CLOSE', 'TRANSITION')",
    )
    op.create_check_constraint(
        op.f("chk_request_transition_edge"),
        "interaction_requests",
        "(kind = 'TRANSITION') = (transition_id IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("chk_request_transition_target"),
        "interaction_requests",
        "kind <> 'TRANSITION' OR (target_stage_id IS NOT NULL "
        "AND target_manager_id IS NULL)",
    )
    op.drop_constraint(
        op.f("chk_stage_history_kind"), "interaction_stage_history", type_="check"
    )
    op.create_check_constraint(
        op.f("chk_stage_history_kind"),
        "interaction_stage_history",
        "kind IN ('TRANSITION', 'CLOSE', 'REOPEN', 'RELOCATION', "
        "'REJECTION', 'ROLLBACK')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("chk_stage_history_kind"), "interaction_stage_history", type_="check"
    )
    op.create_check_constraint(
        op.f("chk_stage_history_kind"),
        "interaction_stage_history",
        "kind IN ('TRANSITION', 'CLOSE', 'REOPEN', 'RELOCATION')",
    )
    op.drop_constraint(
        op.f("chk_request_transition_target"), "interaction_requests", type_="check"
    )
    op.drop_constraint(
        op.f("chk_request_transition_edge"), "interaction_requests", type_="check"
    )
    op.drop_constraint(op.f("chk_request_kind"), "interaction_requests", type_="check")
    op.create_check_constraint(
        op.f("chk_request_kind"), "interaction_requests", "kind IN ('TRANSFER', 'CLOSE')"
    )
    op.drop_constraint(
        op.f("chk_transition_reject_needs_approval"), "workflow_transitions", type_="check"
    )
    op.drop_constraint(
        op.f("chk_transition_approval_not_on_entry"), "workflow_transitions", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_transitions', sa.Column('required_actions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_workflow_transitions_reject_to_stage_id_stages'), 'workflow_transitions', type_='foreignkey')
    op.drop_column('workflow_transitions', 'required_document_kinds')
    op.drop_column('workflow_transitions', 'is_irreversible')
    op.drop_column('workflow_transitions', 'is_backward')
    op.drop_column('workflow_transitions', 'reject_to_stage_id')
    op.drop_column('workflow_transitions', 'requires_approval')
    op.drop_column('stages', 'fields')
    op.drop_constraint(op.f('fk_interaction_requests_transition_id_workflow_transitions'), 'interaction_requests', type_='foreignkey')
    op.drop_column('interaction_requests', 'transition_id')
    op.drop_index(op.f('ix_interaction_stage_values_interaction_id'), table_name='interaction_stage_values')
    op.drop_table('interaction_stage_values')
    # ### end Alembic commands ###
