"""closing a signed interaction closes open branches with a reason

Revision ID: cdcfeb828b5f
Revises: 4bc9989d204c
Create Date: 2026-09-27 19:05:17.232670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdcfeb828b5f"
down_revision: Union[str, Sequence[str], None] = "4bc9989d204c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches",
        sa.Column(
            "closed_with_interaction",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "interaction_requests",
        sa.Column("branch_close_reason_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_interaction_requests_branch_close_reason_id_close_reasons"),
        "interaction_requests",
        "close_reasons",
        ["branch_close_reason_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_interaction_requests_branch_close_reason_id_close_reasons"),
        "interaction_requests",
        type_="foreignkey",
    )
    op.drop_column("interaction_requests", "branch_close_reason_id")
    op.drop_column("branches", "closed_with_interaction")
    # ### end Alembic commands ###
