"""attachment title and category for templates

Revision ID: e5129f779dab
Revises: ea8975536d41
Create Date: 2026-09-29 20:34:17.537939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5129f779dab'
down_revision: Union[str, Sequence[str], None] = 'ea8975536d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('attachments', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_attachments_category'), 'attachments', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_category'), table_name='attachments')
    op.drop_column('attachments', 'category')
    op.drop_column('attachments', 'title')
    # ### end Alembic commands ###
