"""interaction closed and signed marks, one open per university

Revision ID: f938482991a0
Revises: 8503cc10d677
Create Date: 2026-09-27 17:56:29.855376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f938482991a0"
down_revision: Union[str, Sequence[str], None] = "8503cc10d677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions",
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "interactions",
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("interactions", sa.Column("planned_date", sa.Date(), nullable=True))
    op.create_index(
        op.f("ix_interactions_closed_at"), "interactions", ["closed_at"], unique=False
    )
    op.create_index(
        "uq_interactions_open_per_university",
        "interactions",
        ["university_id"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_interactions_open_per_university",
        table_name="interactions",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index(op.f("ix_interactions_closed_at"), table_name="interactions")
    op.drop_column("interactions", "planned_date")
    op.drop_column("interactions", "signed_at")
    op.drop_column("interactions", "closed_at")
    # ### end Alembic commands ###
