"""universities by inn and kpp, shared encrypted contacts

Revision ID: fb8ad264cb0f
Revises: 950a0ef5f9b3
Create Date: 2026-09-27 14:05:58.583738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb8ad264cb0f'
down_revision: Union[str, Sequence[str], None] = '950a0ef5f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('contact_methods', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_actual', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(university_id IS NULL) <> (vendor_id IS NULL)', name=op.f('chk_contact_one_owner')),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_contacts_university_id_universities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_contacts_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_university_id'), 'contacts', ['university_id'], unique=False)
    op.create_index(op.f('ix_contacts_vendor_id'), 'contacts', ['vendor_id'], unique=False)
    op.drop_index(op.f('ix_university_contacts_university_id'), table_name='university_contacts')
    op.drop_index(op.f('uq_university_contacts_primary'), table_name='university_contacts', postgresql_where='(is_primary AND is_actual)')
    op.drop_table('university_contacts')
    op.add_column('products', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_products_contact_id_contacts'), 'products', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.add_column('universities', sa.Column('full_name', sa.Text(), nullable=False))
    op.add_column('universities', sa.Column('short_name', sa.String(length=255), nullable=False))
    op.add_column('universities', sa.Column('inn', sa.String(length=10), nullable=False))
    op.add_column('universities', sa.Column('kpp', sa.String(length=9), nullable=True))
    op.add_column('universities', sa.Column('site', sa.String(length=255), nullable=True))
    op.add_column('universities', sa.Column('region', sa.String(length=255), nullable=False))
    op.add_column('universities', sa.Column('city', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.create_index(op.f('ix_universities_short_name'), 'universities', ['short_name'], unique=False)
    op.create_index('uq_universities_inn_kpp', 'universities', ['inn', 'kpp'], unique=True, postgresql_nulls_not_distinct=True)
    op.drop_column('universities', 'contacts')
    op.drop_column('universities', 'name')
    op.add_column('vendors', sa.Column('site', sa.String(length=255), nullable=True))
    op.add_column('vendors', sa.Column('kind', sa.String(length=255), nullable=True))
    op.drop_column('vendors', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('contacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('vendors', 'kind')
    op.drop_column('vendors', 'site')
    op.add_column('universities', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('contacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index('uq_universities_inn_kpp', table_name='universities', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_universities_short_name'), table_name='universities')
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.drop_column('universities', 'city')
    op.drop_column('universities', 'region')
    op.drop_column('universities', 'site')
    op.drop_column('universities', 'kpp')
    op.drop_column('universities', 'inn')
    op.drop_column('universities', 'short_name')
    op.drop_column('universities', 'full_name')
    op.drop_constraint(op.f('fk_products_contact_id_contacts'), 'products', type_='foreignkey')
    op.drop_column('products', 'contact_id')
    op.create_table('university_contacts',
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_actual', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_university_contacts_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_university_contacts'))
    )
    op.create_index(op.f('uq_university_contacts_primary'), 'university_contacts', ['university_id'], unique=True, postgresql_where='(is_primary AND is_actual)')
    op.create_index(op.f('ix_university_contacts_university_id'), 'university_contacts', ['university_id'], unique=False)
    op.drop_index(op.f('ix_contacts_vendor_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_university_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
